modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "testccessories"
version = "${version}"
displayName = "Testccessories"
authors = "chyzman"
description = '''
Testmod for accessories
'''
#logoFile = ""

[[dependencies.testccessories]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testccessories]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"